#!/bin/bash
IP=$(wget -qO- ipv4.icanhazip.com)
 
echo -e ""
echo -e "**************************************"
echo -e "     How many people can connect ?"​
echo -e ""
echo -e "     [1]  30 people"
echo -e "     [2]  60 people"
echo -e "     [3]  250 people"
echo -e "     [4]  500 people"
echo -e "     [5]  1020 people"
echo -e "     [6]  unlimited people"
echo -e "     [x]  cancel"
echo -e "**************************************"
echo -e ""
read -p "    Please select option [1-6 or x] :  " mask
echo -e ""
case $mask in
1)
cat > /etc/openvpn/server.conf <<-END
port 443
proto tcp
dev tun
sndbuf 0
rcvbuf 0
ca ca.pem
cert server-cert.pem
key server-key.pem
dh dh.pem
#tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.224
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
float
cipher none
comp-lzo yes
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
management $IP 5555
verb 3
#crl-verify crl.pem
client-to-client
client-cert-not-required
username-as-common-name
plugin /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so login
duplicate-cn
END
/etc/init.d/openvpn restart
;;

2)
cat > /etc/openvpn/server.conf <<-END
port 443
proto tcp
dev tun
sndbuf 0
rcvbuf 0
ca ca.pem
cert server-cert.pem
key server-key.pem
dh dh.pem
#tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.128
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
float
cipher none
comp-lzo yes
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
management $IP 5555
verb 3
#crl-verify crl.pem
client-to-client
client-cert-not-required
username-as-common-name
plugin /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so login
duplicate-cn
END
/etc/init.d/openvpn restart
;;

3)
cat > /etc/openvpn/server.conf <<-END
port 443
proto tcp
dev tun
sndbuf 0
rcvbuf 0
ca ca.pem
cert server-cert.pem
key server-key.pem
dh dh.pem
#tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
float
cipher none
comp-lzo yes
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
management $IP 5555
verb 3
#crl-verify crl.pem
client-to-client
client-cert-not-required
username-as-common-name
plugin /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so login
duplicate-cn
END
/etc/init.d/openvpn restart
;;

4)
cat > /etc/openvpn/server.conf <<-END
port 443
proto tcp
dev tun
sndbuf 0
rcvbuf 0
ca ca.pem
cert server-cert.pem
key server-key.pem
dh dh.pem
#tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.254.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
float
cipher none
comp-lzo yes
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
management $IP 5555
verb 3
#crl-verify crl.pem
client-to-client
client-cert-not-required
username-as-common-name
plugin /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so login
duplicate-cn
END
/etc/init.d/openvpn restart
;;

5)
cat > /etc/openvpn/server.conf <<-END
port 443
proto tcp
dev tun
sndbuf 0
rcvbuf 0
ca ca.pem
cert server-cert.pem
key server-key.pem
dh dh.pem
#tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.252.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
float
cipher none
comp-lzo yes
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
management $IP 5555
verb 3
#crl-verify crl.pem
client-to-client
client-cert-not-required
username-as-common-name
plugin /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so login
duplicate-cn
END
/etc/init.d/openvpn restart
;;

6)
cat > /etc/openvpn/server.conf <<-END
port 443
proto tcp
dev tun
sndbuf 0
rcvbuf 0
ca ca.pem
cert server-cert.pem
key server-key.pem
dh dh.pem
#tls-auth ta.key 0
topology subnet
server 10.8.0.0 255.255.248.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
keepalive 10 120
float
cipher none
comp-lzo yes
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
management $IP 5555
verb 3
#crl-verify crl.pem
client-to-client
client-cert-not-required
username-as-common-name
plugin /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so login
duplicate-cn
END
/etc/init.d/openvpn restart
;;
x)
clear
menu
;;
*)
echo "โปรดใส่คำสั่งให้ถูกต้อง"
;;
esac
