#!/bin/bash
echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ DNS ကို Crowfair သို့ ဦးစွာထည့်ရပါမည်။  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " dns

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ root username root only  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " root

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ ဆာဗာ စကားဝှက်  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " pass

curl "https://spnet-vpn.com/add_free.php?update_free=true&ip=$dns&quser=$root&qpass=$pass"


clear
echo "
ဆက်တင်များ ပြီးပါပြီ
"

sleep 5

menu
