#!/bin/bash
echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ DNS must be added to Cloudflare first  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " dns

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ username root only  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " root

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ Server password  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " pass

curl "https://sksvpn.com/add_free.php?update_free=true&ip=$dns&quser=$root&qpass=$pass"


clear
echo "
Settings are complete
"

sleep 5

menu
