#!/bin/bash
echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ စကားဝှက်ထည့်ပါ root  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " pass

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ အွန်လိုင်းရှိသည့်အခါ ပြန်လည်စတင်ရန် အချိန်ဖြစ်သည် 0 ဦးရေရေ"
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " time
rm -r /var/www/html/*

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ လိုင်းတိုကင်  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " token

apt install php -y

wget https://github.com/sansoe2022/own-sshplus-script/raw/main/auto_rebot.zip

unzip -o auto_rebot.zip

mv /root/index.php /var/www/html
mv /root/server_fix.php /var/www/html
mv /root/Crypt /var/www/html
mv /root/Math /var/www/html
mv /root/Net /var/www/html
mv /root/server /var/www/html

cat > /var/spool/cron/crontabs/root <<-auto
@daily /bin/verifatt
@reboot /etc/autostart
* * * * * /etc/autostart
0 */6 * * * /bin/uexpired
*/$time * * * * curl http://$(wget -qO- ipv4.icanhazip.com):82/server_fix.php
@reboot /usr/bin/autoiptables
auto

sleep 4

sed -i 's/xxxx/Spnet@1212/g' /var/www/html/server_fix.php

/etc/init.d/cron reload

clear
echo "
စနစ်ထည့်သွင်းမှု ပြီးပါပြီ
"

curl http://$(wget -qO- ipv4.icanhazip.com):82/server_fix.php
sleep 5
