#!/bin/bash
clear
echo ""
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[0;32m        TRANSLATE BY San Soe  Modified                  \033[0m"
echo -e "\033[0;32m        Telegram ID : https://t.me/sansoe2021                        \033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
backbot=$1
[[ -z $backbot ]] && {
	IP=$(wget -qO- ipv4.icanhazip.com)
	apchon () {
		if netstat -nltp|grep 'dropbear' > /dev/null; then
			[[ ! -d /var/www/html ]] && mkdir /var/www/html
			[[ ! -d /var/www/html/backup ]] && mkdir /var/www/html/backup
			touch /var/www/html/backup/index.html
			/etc/init.d/apache2 restart
		else
			apt-get install apache2 zip -y
			sed -i "s/Listen 80/Listen 81/g" /etc/apache2/ports.conf
			service apache2 restart
			[[ ! -d /var/www/html ]] && mkdir /var/www/html
			[[ ! -d /var/www/html/backup ]] && mkdir /var/www/html/backup
			touch /var/www/html/backup/index.html
			chmod -R 755 /var/www
			/etc/init.d/apache2 restart
		fi
	}
	fun_temp () {
		helice () {
			apchon > /dev/null 2>&1 & 
			tput civis
			while [ -d /proc/$! ]
			do
				for i in / - \\ \|
				do
					sleep .1
					echo -ne "\e[1D$i"
				done
			done
			tput cnorm
		}
		echo -ne "\033[1;33mWAIT\033[1;31m.\033[1;32m.\033[1;33m. \033[1;32m"
		helice
		echo -e "\e[1DOk"
	}
	geralink () {
		if [ -d /var/www/html/backup ]; then
			rm -rf /var/www/html/backup/backup.vps > /dev/null 2>&1
			cp $HOME/backup.vps /var/www/html/backup/backup.vps
			sleep 2
		fi
	}
	fun_temp2 () {
		helice () {
			geralink > /dev/null 2>&1 & 
			tput civis
			while [ -d /proc/$! ]
			do
				for i in / - \\ \|
				do
					sleep .1
					echo -ne "\e[1D$i"
				done
			done
			tput cnorm
		}
		echo -ne "\033[1;33mGENERATING LINK\033[1;31m.\033[1;32m.\033[1;33m. \033[1;32m"
		helice
		echo -e "\e[1DOk"
	}
	echo -e "\E[44;1;37m             Backup Manager              \E[0m"
	echo ""
	echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCreate a backup file \033[1;37m"
	echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mRestore user (admin) \033[1;37m"
	echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mAdd User VPN\033[1;37m"
    echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mRestore user by IP (SKS script)\033[1;37m"
	echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mCancel \033[1;37m"
	echo ""
	echo -ne "\033[1;32mWHAT DO YOU WANT TO DO\033[1;31m ?\033[1;37m : "; read opcao
	if [[ "$opcao" = '1' ]]; then
		if [ -f "/root/usuarios.db" ]
		then
			rm -rf $HOME/backup.vps > /dev/null 2>&1
			sleep 1
			tar cvf /root/backup.vps /root/usuarios.db /etc/shadow /etc/passwd /etc/group /etc/gshadow > /dev/null 2>&1
			echo ""
			echo -e "\033[1;32mBACKUP SUCCESSFULLY CREATED !\033[0m"
			echo ""
			echo -ne "\033[1;32mGENERATE DOWNLOAD LINK \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read resp
			if [[ "$resp" = "s" ]]; then
				echo ""
				fun_temp
				echo ""
				fun_temp2
				echo ""
				if [ -e /var/www/html/backup/backup.vps ]; then
					if [[ "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
						echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/html/backup/backup.vps\033[0m"
					else
						echo -e "\033[1;32mLINK\033[1;37m: \033[1;36m$IP:81/backup/backup.vps\033[0m"
					fi
				else
					echo -e "\033[1;32mAvailable in\033[1;31m" ~/"backup.vps\033[0m"
				fi
			else
				echo -e "\n\033[1;32mAvailable in\033[1;31m" ~/"backup.vps\033[0m"
				sleep 2
				menu
			fi
		else
			echo ""
			echo -e "\033[1;32mCreating backup...\033[0m"
			echo ""
			tar cvf /root/backup.vps /etc/shadow /etc/passwd /etc/group /etc/gshadow > /dev/null 2>&1
			sleep 2s
			echo ""
			echo -e "\033[1;33mThe file \033[1;32mbackup.vps"
			echo -e "\033[1;33mwas successfully created in the directory \033[1;31m/root\033[0m"
			echo ""
		fi
	fi
	if [[ "$opcao" = '2' ]]; then
clear 
echo  ""
echo  ""
echo  ""
echo -e "\033[1;35m { ----------------------------------------------- }  "
echo -e "\033[1;35m { -------------------San Soe-------------------- }  "
echo -e "\033[1;35m { ----------------------------------------------- }  "
echo -e "\033[1;31m { th1 }                Server 1"
echo -e "\033[1;32m { th2 }                Server 2"
echo -e "\033[1;33m { th3 }                Server 3"
echo -e "\033[1;34m { th4 }                Server 4" 
echo -e "\033[1;34m { th5 }                Server 5" 
echo -e "\033[1;34m { th6 }                Server 6" 
echo -e "\033[1;35m { ----------------------------------------------- }  "
   
    read -p "Enter the name of backup :  " -e bkup
    echo ""
    echo ""
cd /
wget -O /root/$bkup.vps http://$IP:82/backup/$bkup.vps  
		if [ -f "/root/$bkup.vps" ]
		then
			echo ""
			echo -e "\033[1;36min progress..."
			echo ""
			sleep 2s
			cp /root/$bkup.vps /$bkup.vps
			cd /
			tar -xvf $bkup.vps
			rm /$bkup.vps
     echo "=== Complete === "
echo -e "\033[01;35m"

			echo ""
			echo -e "\033[1;36mBackup data\033[1;36m Completed successfully\033[0m"
			echo ""
			exit
		else
			echo ""
			echo -e "\033[1;33mFile \033[1;32m$bkup.vps \033[1;33mBackup file not found!\033[0m"
			echo -e "\033[1;33mBe sure to back up the files \033[1;32m$bkup.vps finish\033[0m"
			echo ""
			exit
		fi
	fi
    if [[ "$opcao" = '3' ]]; then
clear 
echo  ""
echo  ""
echo  ""
echo -e "\033[1;34m"
    echo ""
    echo ""
echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ DNS must be added to CloudFlare first  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " dns

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ Username root only  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " root

echo "
╭━━━━━━━━━━━━━━━━━━━━━━━╮"
echo " ┈┣ Server password  "
echo " ╰━━━━━━━━━━━━━━━━━━━━━━━╯"
read -p " : " pass

curl "https://YourDomain/add_free.php?update_free=true&ip=$dns&quser=$root&qpass=$pass"


clear


			echo -e "\033[1;36mBackup\033[1;36m Completed successfully\033[0m"
			echo ""
			exit
		else
			echo ""
			echo -e "\033[1;33mIf it failed, Is it backed up? Check first \033[1;32m\033[0m"
			echo ""
			exit
		
	fi
    	if [[ "$opcao" = '4' ]]; then
clear 
echo  ""
echo  ""
echo  ""
    read -p "Enter the backup IP :  " -e bkup
    echo ""
    echo ""
cd /
wget -O /root/backup.vps http://$bkup/backup.vps  
		if [ -f "/root/$bkup.vps" ]
		then
			echo ""
			echo -e "\033[1;36min progress..."
			echo ""
			sleep 2s
			cp /root/bankup.vps /backup.vps
			cd /
			tar -xvf backup.vps
			rm /backup.vps
			echo -e "\033[1;36mBackup\033[1;36m Successfully completed\033[0m"
			echo ""
			exit
		else
			echo ""
			echo -e "\033[1;33mFile \033[1;32m$bkup \033[1;33mBackup file not found!\033[0m"
			echo -e "\033[1;33mBe sure to backup the files \033[1;32m$bkup finish\033[0m"
			echo ""
			exit
		fi
	fi

	if [[ "$opcao" = '5' ]]; then
		menu
	fi
} || {
	rm /root/$bkup.vps 1>/dev/null 2>/dev/null
	tar cvf /root/$bkup.vps /root/usuarios.db /etc/shadow /etc/passwd /etc/group /etc/gshadow /etc/bot 1>/dev/null 2>/dev/null
	[[ -d "/etc/SSHPlus/backups" ]] && mv /root/backup.vps /etc/SSHPlus/backups/$bkup.vps
	exit
}
